package org.jonnyzzz.lifegame

val empty get() = Maze3(1,1)

val blinker get() = loadMaze("""
      ...........
      ...x.......
      ...x.......
      ...x.......
      ...........
  """)

val beacon get() = loadMaze("""
      ...........
      ...xx......
      ...xx......
      .....xx....
      .....xx....
      ...........

  """)

val glider get() = loadMaze("""
      ...x.............
      ....x............
      ..xxx............
      .................
      .................
      .................
      .................
      .................
      .................

  """)


fun main() {
  var m = glider

  repeat(30) {
    println(m.renderToString())
    m = m.nextGeneration(EvolutionCell::conwayLaws)
  }
}

