package org.jonnyzzz.lifegame

val empty get() = Maze3(1, 1)

val blinker
  get() = """
      ...........
      ...x.......
      ...x.......
      ...x.......
      ...........
  """.toMaze()

val beacon
  get() = """
      ...........
      ...xx......
      ...xx......
      .....xx....
      .....xx....
      ...........
  """.toMaze()

val glider
  get() = """
      ...x.............
      ....x............
      ..xxx............
      .................
      .................
      .................
      .................
      .................
      .................
  """.toMaze()


fun main() {
  var m = """
      ...x.....
      ....x....
      ..xxx....
      .........
      .........
  """.toMaze()

  repeat(5) {
    println()
    println(m.renderToString())
    m = m.nextGeneration(EvolutionCell::conwayLaws)
  }
}

